# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pmvic_db
spring.datasource.username=pmvic_db_user
spring.datasource.password=password

# -- Spring Boot auto configures JDBC driver
# spring.datasource.driver-class-name=org.postgresql.Driver
